# List the files in the same directory of the .ipynb file

In [1]:
import os
print(os.listdir("/Users/gladia2or/Documents/School/Fall 18/Machine Learning/assignments/miniProject2"))

['iris1.csv', 'iris2.csv', '.DS_Store', 'iris.html', 'Mini-projet-application2.pdf', 'iris1 copy.csv', 'iris.csv', 'Mini-project-application2-new.pdf', '.ipynb_checkpoints', 'miniProject2.ipynb']


# Import the data

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import datasets
%matplotlib inline

iris=pd.read_csv('../miniProject2/iris2.csv')
# iris = datasets.load_iris()
# data = iris.data[:,[2,3]]
# iris_df = pd.DataFrame(iris.data[:, [2, 3]], columns=iris.feature_names[2:])

# View the first elements in the dataset

In [3]:
iris.head()

petal_length  petal_width      species
0           1.4         0.02  Iris-setosa
1           1.4         0.20  Iris-setosa
2           1.3         0.20  Iris-setosa
3           1.5         0.20  Iris-setosa
4           1.4         0.20  Iris-setosa

In [4]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 3 columns):
petal_length    150 non-null float64
petal_width     150 non-null float64
species         150 non-null object
dtypes: float64(2), object(1)
memory usage: 3.6+ KB


# Split the data into a tran & test set

In [5]:
from sklearn.model_selection import train_test_split
# X is the data
x=iris.iloc[:,:-1]
# Y is the answers
y=iris.iloc[:,2]

x_train,x_test, y_train, y_test=train_test_split(x,y,test_size=0.20)
# x.head()
# y.head()
print (x_train.shape, y_train.shape) 
print (x_test.shape, y_test.shape) 
# print(x)
# print(y)

(120, 2) (120,)
(30, 2) (30,)


# Fit the model

In [6]:
from sklearn import svm
clf = svm.SVC(kernel='linear', C=1).fit(x_train, y_train) 
# print(clf.score(x_test, y_test))

# Make predictions

In [7]:
pred=clf.predict(x_test)
# print(pred)

# Evaluate the predictions

In [8]:
from sklearn.metrics import confusion_matrix
print("\nConfusion Matrix\n",confusion_matrix(y_test,pred))
from sklearn.metrics import precision_score
print("\nPrecision Score (weighted)\n",precision_score(y_test,pred,average='weighted'))
from sklearn.metrics import recall_score
print("\nRecall Score (weighted)\n",recall_score(y_test,pred,average='weighted'))
from sklearn.metrics import f1_score
print("\nF1 Score (weighted)\n",f1_score(y_test,pred,average='weighted'))


Confusion Matrix
 [[ 6  0  0]
 [ 0 10  0]
 [ 0  0 14]]

Precision Score (weighted)
 1.0

Recall Score (weighted)
 1.0

F1 Score (weighted)
 1.0


In [9]:
from sklearn.svm import SVC
# svm= SVC()

# Grid serarch to find the best parameters
## I used parameters found at scikit-learn.org

In [10]:
from sklearn.model_selection import GridSearchCV

parameters = {'kernel':('linear', 'rbf'), 'C':[1, 10]}
grid = GridSearchCV(SVC(),parameters,refit=True,cv=5,verbose=1)
grid.fit(x_train,y_train)

grid_predictions = grid.predict(x_test)

Fitting 5 folds for each of 4 candidates, totalling 20 fits


[Parallel(n_jobs=1)]: Done  20 out of  20 | elapsed:    0.1s finished


# Evaluate new predictions

In [11]:
from sklearn.metrics import confusion_matrix
print("\nConfusion Matrix\n",confusion_matrix(y_test,grid_predictions))
from sklearn.metrics import precision_score
print("\nPrecision Score (weighted)\n",precision_score(y_test,grid_predictions,average='weighted'))
from sklearn.metrics import recall_score
print("\nRecall Score (weighted)\n",recall_score(y_test,grid_predictions,average='weighted'))
from sklearn.metrics import f1_score
print("\nF1 Score (weighted)\n",f1_score(y_test,grid_predictions,average='weighted'))


Confusion Matrix
 [[ 6  0  0]
 [ 0 10  0]
 [ 0  0 14]]

Precision Score (weighted)
 1.0

Recall Score (weighted)
 1.0

F1 Score (weighted)
 1.0


# Our results both ways are always either the same or extremely close to one another